import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { isValidArd, ARD_INVALID_MSG } from "@/services/search";
import { getStock } from "@/services/scrapers/eposScraper";
import { isScrapeError } from "@/services/errors";
import { buildAvailability } from "@/lib/availability";
import { ErrorState } from "@/components/shared/error-state";
import { AvailabilityPanel } from "@/components/shared/availability-panel";
import { SOURCES } from "@/lib/constants";

export const dynamic = "force-dynamic";
/** Serverless hosts: allow time for polite, cold scrapes of government servers. */
export const maxDuration = 60;

export async function generateMetadata({ params }: { params: Promise<{ ard: string }> }): Promise<Metadata> {
  const { ard } = await params;
  return {
    title: `Ration Availability ${ard}`,
    description: `Latest ration commodity availability for Kerala ration shop ARD ${ard}.`,
  };
}

export default async function AvailabilityPage({ params }: { params: Promise<{ ard: string }> }) {
  const { ard } = await params;

  if (!isValidArd(ard)) {
    return (
      <div className="container-max py-10">
        <ErrorState title="Invalid ARD Number" message={ARD_INVALID_MSG} />
      </div>
    );
  }

  let snapshot;
  try {
    snapshot = await getStock(ard);
  } catch (err) {
    if (isScrapeError(err)) {
      return (
        <div className="container-max py-10">
          <ErrorState
            title="Availability information unavailable"
            message={err.userMessage}
            href={`/store/${ard}`}
            linkLabel="Back to store"
          />
        </div>
      );
    }
    notFound();
  }

  const availability = buildAvailability(snapshot);

  return (
    <div className="container-max py-8">
      <Link href={`/store/${ard}`} className="text-sm font-medium text-blue-700 hover:underline">
        ← Back to Store Details
      </Link>

      <div className="mt-4 max-w-3xl">
        <h1 className="text-2xl font-extrabold text-slate-900 md:text-3xl">
          <span aria-hidden="true">📦</span> Current Ration Availability
        </h1>
        <p className="mt-1 text-sm text-muted-foreground">
          ARD {ard} · Live data from the official Kerala AePDS / ePOS public portal.
        </p>

        <div className="mt-6">
          <legend className="mb-2 flex flex-wrap gap-2 text-xs text-muted-foreground">
            <span>🟢 Available</span>
            <span>🟡 Limited Stock</span>
            <span>🔴 Out of Stock</span>
            <span>⚪ No Data</span>
          </legend>
          <AvailabilityPanel initial={availability} ardNumber={ard} />
        </div>

        <p className="mt-6 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">
          <strong>Disclaimer:</strong> Ration availability information is collected from
          publicly available official sources. Actual stock availability may change. Users
          are advised to contact the respective ration shop or authorities before visiting.
        </p>

        <p className="mt-4 text-xs text-muted-foreground">
          Source: {SOURCES.epos} (public ePOS report generated by the Civil Supplies
          Department). Status is auto-computed from the monthly closing balance reported by
          the government for this shop.
        </p>
      </div>
    </div>
  );
}